application: dr-json
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  mime_type: "text/css"

- url: .*
  script: views.py

builtins:
- admin_redirect: on
- datastore_admin: on
- deferred: on
- remote_api: on
